"""伺服器儲存後端：Postgres（關聯資料）+ pgvector（向量檢索）。

行為與 SqliteFaissStore 1:1 對應（同一套 tests/test_store.py 行為測試）。
向量存獨立 paper_embeddings 表（無維度宣告，維度跟隨 embedder，小規模
用精確搜尋；需要 ivfflat/hnsw 索引時再固定維度）。單一連線 + 執行緒鎖，
embedder 可注入以利離線測試。
"""
import json
import secrets
import threading
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row

from src import config
from src.rag.vector_store import _lexical_overlap, _tokenize
from src.store.base import Store
from src.utils.logger import get_logger

_SCHEMA = """
CREATE TABLE IF NOT EXISTS papers (
    id         TEXT PRIMARY KEY,
    title      TEXT NOT NULL,
    abstract   TEXT,
    authors    TEXT,
    link       TEXT,
    published  TEXT,
    summary    TEXT,
    source     TEXT DEFAULT 'arxiv',
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS interactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id   TEXT REFERENCES papers(id),
    user_id    TEXT,
    action     TEXT NOT NULL,
    value      DOUBLE PRECISION DEFAULT 1.0,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_interactions_paper  ON interactions(paper_id);
CREATE INDEX IF NOT EXISTS idx_interactions_action ON interactions(action);
CREATE INDEX IF NOT EXISTS idx_papers_published    ON papers(published);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    google_sub    TEXT,
    github_id     TEXT,
    discord_id    TEXT,
    display_name  TEXT,
    locale        TEXT DEFAULT 'en',
    created_at    TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS feeds (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    url        TEXT NOT NULL,
    title      TEXT,
    category   TEXT,
    enabled    BOOLEAN DEFAULT TRUE,
    created_at TEXT NOT NULL,
    UNIQUE (user_id, url)
);
CREATE TABLE IF NOT EXISTS user_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    name       TEXT NOT NULL,
    keywords   TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (user_id, name)
);
CREATE TABLE IF NOT EXISTS conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    title       TEXT DEFAULT '',
    share_token TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id);
CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role            TEXT NOT NULL,
    content         TEXT NOT NULL,
    citations       TEXT,
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages(conversation_id);
CREATE TABLE IF NOT EXISTS reading_list (
    user_id    BIGINT NOT NULL,
    paper_id   TEXT NOT NULL,
    title      TEXT,
    state      TEXT DEFAULT 'to-read',
    tags       TEXT,
    note       TEXT DEFAULT '',
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, paper_id)
);
CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id     BIGINT PRIMARY KEY,
    frequency   TEXT DEFAULT 'daily',
    hour        INTEGER DEFAULT 9,
    minute      INTEGER DEFAULT 0,
    timezone    TEXT DEFAULT 'Asia/Taipei',
    quiet_start INTEGER,
    quiet_end   INTEGER,
    min_score   DOUBLE PRECISION DEFAULT 0.0,
    dedupe      BOOLEAN DEFAULT TRUE,
    channels    TEXT
);
CREATE TABLE IF NOT EXISTS reminders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    text       TEXT NOT NULL,
    due_at     TEXT NOT NULL,
    context    TEXT,
    done       BOOLEAN DEFAULT FALSE,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS learning_paths (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    topic      TEXT NOT NULL,
    items      TEXT NOT NULL,
    progress   TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS user_skills (
    user_id    BIGINT NOT NULL,
    skill      TEXT NOT NULL,
    level      DOUBLE PRECISION DEFAULT 0,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, skill)
);
CREATE TABLE IF NOT EXISTS paper_embeddings (
    paper_id  TEXT PRIMARY KEY REFERENCES papers(id) ON DELETE CASCADE,
    embedding vector NOT NULL
);
"""

_USER_OAUTH_FIELDS = ("google_sub", "github_id", "discord_id")
_READING_STATES = ("to-read", "reading", "done")
_PREF_DEFAULTS = {
    "frequency": "daily", "hour": 9, "minute": 0, "timezone": "Asia/Taipei",
    "quiet_start": None, "quiet_end": None, "min_score": 0.0,
    "dedupe": True, "channels": ["web"],
}


def _now():
    return datetime.now(timezone.utc).isoformat()


def _loads(text, default):
    if not text:
        return default
    try:
        return json.loads(text)
    except (TypeError, ValueError):
        return default


class _VectorShim:
    """duck-type rag.VectorStore 的最小介面（LibraryService 取 embedder 用）。"""

    index = None

    def __init__(self, store):
        self._store = store

    @property
    def embedder(self):
        return self._store.embedder


class PostgresPgvectorStore(Store):
    def __init__(self, dsn=None, embedder=None):
        self.logger = get_logger(self.__class__.__name__)
        self.dsn = dsn or config.DATABASE_URL
        if not self.dsn:
            raise ValueError("postgres 後端需要 DATABASE_URL")
        self._lock = threading.Lock()
        self._conn = psycopg.connect(self.dsn, row_factory=dict_row, autocommit=True)
        self._conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
        from pgvector.psycopg import register_vector
        register_vector(self._conn)
        # psycopg3 extended protocol 不接受多語句，逐句建 schema
        for stmt in _SCHEMA.split(";"):
            if stmt.strip():
                self._conn.execute(stmt)
        self._embedder = embedder
        self._shim = _VectorShim(self)
        self.logger.info("Postgres+pgvector store 就緒")

    # embedding 模型很重，只有向量操作才載
    @property
    def embedder(self):
        if self._embedder is None:
            from sentence_transformers import SentenceTransformer
            self._embedder = SentenceTransformer(config.EMBED_MODEL)
        return self._embedder

    @property
    def vector(self):
        return self._shim

    def _exec(self, sql, params=()):
        with self._lock:
            return self._conn.execute(sql, params)

    def _one(self, sql, params=()):
        return self._exec(sql, params).fetchone()

    def _all(self, sql, params=()):
        return self._exec(sql, params).fetchall()

    # ---- 使用者 ----
    def create_user(self, email, password_hash=None, display_name=None,
                    locale="en", google_sub=None, github_id=None, discord_id=None):
        email = email.strip().lower()
        try:
            row = self._one(
                "INSERT INTO users (email, password_hash, google_sub, github_id, discord_id,"
                " display_name, locale, created_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
                " RETURNING id",
                (email, password_hash, google_sub, github_id, discord_id,
                 display_name or email.split("@")[0], locale, _now()),
            )
        except psycopg.errors.UniqueViolation:
            raise ValueError(f"email 已註冊：{email}")
        return self.get_user(row["id"])

    def get_user(self, user_id):
        return self._one("SELECT * FROM users WHERE id = %s", (user_id,))

    def get_user_by_email(self, email):
        return self._one("SELECT * FROM users WHERE email = %s", (email.strip().lower(),))

    def all_users(self):
        return self._all("SELECT * FROM users ORDER BY id")

    def get_user_by_oauth(self, field, value):
        if field not in _USER_OAUTH_FIELDS:
            raise ValueError(f"未知 OAuth 欄位：{field}")
        return self._one(f"SELECT * FROM users WHERE {field} = %s", (str(value),))

    def update_user(self, user_id, **fields):
        allowed = {"password_hash", "display_name", "locale", *_USER_OAUTH_FIELDS}
        updates = {k: v for k, v in fields.items() if k in allowed}
        if updates:
            sets = ", ".join(f"{k} = %s" for k in updates)
            self._exec(f"UPDATE users SET {sets} WHERE id = %s", (*updates.values(), user_id))
        return self.get_user(user_id)

    # ---- 論文 / 互動 ----
    def upsert_papers(self, papers):
        added = 0
        for p in papers:
            row = self._one(
                """
                INSERT INTO papers (id, title, abstract, authors, link, published, summary, source, created_at)
                VALUES (%(id)s, %(title)s, %(abstract)s, %(authors)s, %(link)s,
                        %(published)s, %(summary)s, %(source)s, %(created_at)s)
                ON CONFLICT (id) DO UPDATE SET
                    title=excluded.title, abstract=excluded.abstract, authors=excluded.authors,
                    link=excluded.link, published=excluded.published,
                    summary=COALESCE(excluded.summary, papers.summary),
                    source=excluded.source
                RETURNING (xmax = 0) AS inserted
                """,
                {
                    "id": p["id"], "title": p.get("title", ""), "abstract": p.get("abstract", ""),
                    "authors": p.get("authors", ""), "link": p.get("link", ""),
                    "published": p.get("published", ""), "summary": p.get("summary"),
                    "source": p.get("source", "arxiv"), "created_at": _now(),
                },
            )
            added += bool(row["inserted"])
        return added

    def get_paper(self, paper_id):
        return self._one("SELECT * FROM papers WHERE id = %s", (paper_id,))

    def all_papers(self, limit=None, source=None):
        sql, params = "SELECT * FROM papers", []
        if source:
            sql += " WHERE source = %s"
            params.append(source)
        sql += " ORDER BY published DESC, created_at DESC"
        if limit:
            sql += " LIMIT %s"
            params.append(limit)
        return self._all(sql, params)

    def count_papers(self):
        return self._one("SELECT COUNT(*) AS n FROM papers")["n"]

    def log_interaction(self, action, paper_id=None, user_id=None, value=1.0):
        self._exec(
            "INSERT INTO interactions (paper_id, user_id, action, value, created_at)"
            " VALUES (%s, %s, %s, %s, %s)",
            (paper_id, str(user_id) if user_id is not None else None,
             action, float(value), _now()),
        )

    def interaction_counts(self, action=None):
        sql = ("SELECT paper_id, SUM(value) AS total FROM interactions"
               " WHERE paper_id IS NOT NULL")
        params = []
        if action:
            sql += " AND action = %s"
            params.append(action)
        sql += " GROUP BY paper_id"
        return {r["paper_id"]: float(r["total"]) for r in self._all(sql, params)}

    def action_totals(self, user_id=None):
        sql, params = "SELECT action, COUNT(*) AS n FROM interactions", []
        if user_id is not None:
            sql += " WHERE user_id = %s"
            params.append(str(user_id))
        sql += " GROUP BY action"
        return {r["action"]: r["n"] for r in self._all(sql, params)}

    def user_interactions(self, user_id, limit=200):
        return self._all(
            "SELECT * FROM interactions WHERE user_id = %s ORDER BY created_at DESC LIMIT %s",
            (str(user_id), limit),
        )

    # ---- 向量檢索 ----
    def index_papers(self, papers):
        if not papers:
            return []
        self.upsert_papers(papers)  # 保外鍵；冪等
        texts, fresh = [], []
        for p in papers:
            if self._one("SELECT 1 FROM paper_embeddings WHERE paper_id = %s", (p["id"],)):
                continue
            fresh.append(p)
            texts.append(f"{p.get('title', '')} {p.get('abstract', '')}")
        if not fresh:
            return []
        vecs = self.embedder.encode(texts)
        for p, v in zip(fresh, vecs):
            self._exec(
                "INSERT INTO paper_embeddings (paper_id, embedding) VALUES (%s, %s)"
                " ON CONFLICT (paper_id) DO NOTHING",
                (p["id"], v),
            )
        return fresh

    def search_scored(self, query, k=4, where=None, rerank=True):
        total = self._one("SELECT COUNT(*) AS n FROM paper_embeddings")["n"]
        if total == 0:
            return []
        vec = self.embedder.encode([query])[0]
        fetch_k = min(total, max(k * 4, 20))
        rows = self._all(
            """
            SELECT p.*, 1 - (e.embedding <=> %s) AS score
            FROM paper_embeddings e JOIN papers p ON p.id = e.paper_id
            ORDER BY e.embedding <=> %s LIMIT %s
            """,
            (vec, vec, fetch_k),
        )
        cands = []
        for r in rows:
            score = float(r.pop("score"))
            if where is not None and not where(r):
                continue
            cands.append((r, score))
        if rerank and cands:
            q_tokens = _tokenize(query)
            cands = [
                (p, 0.7 * s + 0.3 * _lexical_overlap(
                    q_tokens, f"{p.get('title', '')} {p.get('abstract', '')}"))
                for p, s in cands
            ]
            cands.sort(key=lambda it: it[1], reverse=True)
        return cands[:k]

    # ---- RSS feeds ----
    def add_feed(self, user_id, url, title=None, category=None):
        try:
            row = self._one(
                "INSERT INTO feeds (user_id, url, title, category, created_at)"
                " VALUES (%s, %s, %s, %s, %s) RETURNING id",
                (user_id, url.strip(), title, category, _now()),
            )
        except psycopg.errors.UniqueViolation:
            raise ValueError(f"已訂閱過此來源:{url}")
        return self._feed(row["id"])

    def _feed(self, feed_id):
        row = self._one("SELECT * FROM feeds WHERE id = %s", (feed_id,))
        if row:
            row["enabled"] = bool(row["enabled"])
        return row

    def list_feeds(self, user_id):
        rows = self._all(
            "SELECT * FROM feeds WHERE user_id = %s ORDER BY created_at", (user_id,)
        )
        for r in rows:
            r["enabled"] = bool(r["enabled"])
        return rows

    def update_feed(self, feed_id, user_id, **fields):
        allowed = {"url", "title", "category", "enabled"}
        updates = {k: (bool(v) if k == "enabled" else v)
                   for k, v in fields.items() if k in allowed}
        if updates:
            sets = ", ".join(f"{k} = %s" for k in updates)
            cur = self._exec(
                f"UPDATE feeds SET {sets} WHERE id = %s AND user_id = %s",
                (*updates.values(), feed_id, user_id),
            )
            if cur.rowcount == 0:
                return None
        return self._feed(feed_id)

    def delete_feed(self, feed_id, user_id):
        cur = self._exec("DELETE FROM feeds WHERE id = %s AND user_id = %s",
                         (feed_id, user_id))
        return cur.rowcount > 0

    # ---- 主題訂閱 ----
    def add_subscription(self, user_id, name, keywords):
        kws = json.dumps([k.lower() for k in keywords], ensure_ascii=False)
        self._exec(
            "INSERT INTO user_subscriptions (user_id, name, keywords, created_at)"
            " VALUES (%s, %s, %s, %s)"
            " ON CONFLICT (user_id, name) DO UPDATE SET keywords=excluded.keywords",
            (user_id, name, kws, _now()),
        )
        return {"name": name, "keywords": _loads(kws, [])}

    def list_subscriptions(self, user_id):
        rows = self._all(
            "SELECT name, keywords FROM user_subscriptions WHERE user_id = %s"
            " ORDER BY created_at",
            (user_id,),
        )
        return [{"name": r["name"], "keywords": _loads(r["keywords"], [])} for r in rows]

    def remove_subscription(self, user_id, name):
        cur = self._exec(
            "DELETE FROM user_subscriptions WHERE user_id = %s AND name = %s",
            (user_id, name),
        )
        return cur.rowcount > 0

    # ---- 對話 ----
    def create_conversation(self, user_id, title=""):
        now = _now()
        row = self._one(
            "INSERT INTO conversations (user_id, title, created_at, updated_at)"
            " VALUES (%s, %s, %s, %s) RETURNING id",
            (user_id, title, now, now),
        )
        return self._conversation_row(row["id"])

    def _conversation_row(self, conv_id):
        return self._one("SELECT * FROM conversations WHERE id = %s", (conv_id,))

    def list_conversations(self, user_id, query=None, limit=50):
        if query:
            like = f"%{query}%"
            return self._all(
                """
                SELECT DISTINCT c.* FROM conversations c
                LEFT JOIN messages m ON m.conversation_id = c.id
                WHERE c.user_id = %s AND (c.title ILIKE %s OR m.content ILIKE %s)
                ORDER BY c.updated_at DESC LIMIT %s
                """,
                (user_id, like, like, limit),
            )
        return self._all(
            "SELECT * FROM conversations WHERE user_id = %s ORDER BY updated_at DESC LIMIT %s",
            (user_id, limit),
        )

    def get_conversation(self, conv_id, user_id=None):
        conv = self._conversation_row(conv_id)
        if not conv or (user_id is not None and conv["user_id"] != user_id):
            return None
        conv["messages"] = self._messages(conv_id)
        return conv

    def _messages(self, conv_id):
        rows = self._all(
            "SELECT * FROM messages WHERE conversation_id = %s ORDER BY id", (conv_id,)
        )
        for r in rows:
            r["citations"] = _loads(r["citations"], None)
        return rows

    def rename_conversation(self, conv_id, user_id, title):
        cur = self._exec(
            "UPDATE conversations SET title = %s, updated_at = %s"
            " WHERE id = %s AND user_id = %s",
            (title, _now(), conv_id, user_id),
        )
        return cur.rowcount > 0

    def delete_conversation(self, conv_id, user_id):
        cur = self._exec(
            "DELETE FROM conversations WHERE id = %s AND user_id = %s", (conv_id, user_id)
        )
        self._exec("DELETE FROM messages WHERE conversation_id = %s", (conv_id,))
        return cur.rowcount > 0

    def add_message(self, conv_id, role, content, citations=None):
        now = _now()
        row = self._one(
            "INSERT INTO messages (conversation_id, role, content, citations, created_at)"
            " VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (conv_id, role, content,
             json.dumps(citations, ensure_ascii=False) if citations is not None else None,
             now),
        )
        self._exec("UPDATE conversations SET updated_at = %s WHERE id = %s", (now, conv_id))
        return {"id": row["id"], "conversation_id": conv_id, "role": role,
                "content": content, "citations": citations, "created_at": now}

    def share_conversation(self, conv_id, user_id):
        conv = self._conversation_row(conv_id)
        if not conv or conv["user_id"] != user_id:
            return None
        if conv["share_token"]:
            return conv["share_token"]
        token = secrets.token_urlsafe(16)
        self._exec("UPDATE conversations SET share_token = %s WHERE id = %s",
                   (token, conv_id))
        return token

    def get_shared_conversation(self, token):
        conv = self._one("SELECT * FROM conversations WHERE share_token = %s", (token,))
        if not conv:
            return None
        conv["messages"] = self._messages(conv["id"])
        return conv

    # ---- 閱讀看板 ----
    def reading_upsert(self, user_id, paper_id, title, state="to-read", tags=None, note=""):
        if state not in _READING_STATES:
            raise ValueError(f"未知狀態：{state}（可用 {_READING_STATES}）")
        self._exec(
            """
            INSERT INTO reading_list (user_id, paper_id, title, state, tags, note, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id, paper_id) DO UPDATE SET
                title=excluded.title, state=excluded.state, tags=excluded.tags,
                note=excluded.note, updated_at=excluded.updated_at
            """,
            (user_id, paper_id, title, state,
             json.dumps(list(tags or []), ensure_ascii=False), note, _now()),
        )
        return {"id": paper_id, "title": title, "state": state,
                "tags": list(tags or []), "note": note}

    def reading_items(self, user_id, state=None):
        sql, params = "SELECT * FROM reading_list WHERE user_id = %s", [user_id]
        if state:
            sql += " AND state = %s"
            params.append(state)
        sql += " ORDER BY updated_at DESC"
        return [{"id": r["paper_id"], "title": r["title"], "state": r["state"],
                 "tags": _loads(r["tags"], []), "note": r["note"] or ""}
                for r in self._all(sql, params)]

    def reading_set_state(self, user_id, paper_id, state):
        if state not in _READING_STATES:
            raise ValueError(f"未知狀態：{state}")
        cur = self._exec(
            "UPDATE reading_list SET state = %s, updated_at = %s"
            " WHERE user_id = %s AND paper_id = %s",
            (state, _now(), user_id, paper_id),
        )
        return cur.rowcount > 0

    def reading_remove(self, user_id, paper_id):
        cur = self._exec(
            "DELETE FROM reading_list WHERE user_id = %s AND paper_id = %s",
            (user_id, paper_id),
        )
        return cur.rowcount > 0

    # ---- 通知偏好 ----
    def get_notification_prefs(self, user_id):
        row = self._one(
            "SELECT * FROM notification_preferences WHERE user_id = %s", (user_id,)
        )
        if not row:
            return dict(_PREF_DEFAULTS)
        row.pop("user_id", None)
        row["dedupe"] = bool(row["dedupe"])
        row["channels"] = _loads(row["channels"], list(_PREF_DEFAULTS["channels"]))
        return row

    def set_notification_prefs(self, user_id, **fields):
        prefs = self.get_notification_prefs(user_id)
        prefs.update({k: v for k, v in fields.items() if k in _PREF_DEFAULTS})
        self._exec(
            """
            INSERT INTO notification_preferences
                (user_id, frequency, hour, minute, timezone, quiet_start, quiet_end,
                 min_score, dedupe, channels)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id) DO UPDATE SET
                frequency=excluded.frequency, hour=excluded.hour, minute=excluded.minute,
                timezone=excluded.timezone, quiet_start=excluded.quiet_start,
                quiet_end=excluded.quiet_end, min_score=excluded.min_score,
                dedupe=excluded.dedupe, channels=excluded.channels
            """,
            (user_id, prefs["frequency"], prefs["hour"], prefs["minute"], prefs["timezone"],
             prefs["quiet_start"], prefs["quiet_end"], prefs["min_score"],
             bool(prefs["dedupe"]), json.dumps(prefs["channels"], ensure_ascii=False)),
        )
        return prefs

    # ---- 提醒 ----
    def add_reminder(self, user_id, text, due_at, context=None):
        row = self._one(
            "INSERT INTO reminders (user_id, text, due_at, context, created_at)"
            " VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (user_id, text, due_at,
             json.dumps(context, ensure_ascii=False) if context else None, _now()),
        )
        return self._reminder(row["id"])

    def _reminder(self, rid):
        row = self._one("SELECT * FROM reminders WHERE id = %s", (rid,))
        if row:
            row["done"] = bool(row["done"])
            row["context"] = _loads(row["context"], None)
        return row

    def list_reminders(self, user_id, include_done=False):
        sql, params = "SELECT id FROM reminders WHERE user_id = %s", [user_id]
        if not include_done:
            sql += " AND done = FALSE"
        sql += " ORDER BY due_at"
        return [self._reminder(r["id"]) for r in self._all(sql, params)]

    def complete_reminder(self, reminder_id, user_id):
        cur = self._exec(
            "UPDATE reminders SET done = TRUE WHERE id = %s AND user_id = %s",
            (reminder_id, user_id),
        )
        return cur.rowcount > 0

    def delete_reminder(self, reminder_id, user_id):
        cur = self._exec(
            "DELETE FROM reminders WHERE id = %s AND user_id = %s", (reminder_id, user_id)
        )
        return cur.rowcount > 0

    def due_reminders(self, now_iso):
        rows = self._all(
            "SELECT id FROM reminders WHERE done = FALSE AND due_at <= %s ORDER BY due_at",
            (now_iso,),
        )
        return [self._reminder(r["id"]) for r in rows]

    # ---- 學習路徑 / 技能 ----
    def create_learning_path(self, user_id, topic, items):
        now = _now()
        row = self._one(
            "INSERT INTO learning_paths (user_id, topic, items, progress, created_at, updated_at)"
            " VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
            (user_id, topic, json.dumps(items, ensure_ascii=False), "{}", now, now),
        )
        return self._learning_path(row["id"])

    def _learning_path(self, pid):
        row = self._one("SELECT * FROM learning_paths WHERE id = %s", (pid,))
        if row:
            row["items"] = _loads(row["items"], [])
            row["progress"] = _loads(row["progress"], {})
        return row

    def list_learning_paths(self, user_id):
        rows = self._all(
            "SELECT id FROM learning_paths WHERE user_id = %s ORDER BY updated_at DESC",
            (user_id,),
        )
        return [self._learning_path(r["id"]) for r in rows]

    def update_learning_path(self, path_id, user_id, **fields):
        allowed = {"topic", "items", "progress"}
        updates = {}
        for k, v in fields.items():
            if k not in allowed:
                continue
            updates[k] = json.dumps(v, ensure_ascii=False) if k in ("items", "progress") else v
        if updates:
            updates["updated_at"] = _now()
            sets = ", ".join(f"{k} = %s" for k in updates)
            cur = self._exec(
                f"UPDATE learning_paths SET {sets} WHERE id = %s AND user_id = %s",
                (*updates.values(), path_id, user_id),
            )
            if cur.rowcount == 0:
                return None
        return self._learning_path(path_id)

    def delete_learning_path(self, path_id, user_id):
        cur = self._exec(
            "DELETE FROM learning_paths WHERE id = %s AND user_id = %s", (path_id, user_id)
        )
        return cur.rowcount > 0

    def set_skill(self, user_id, skill, level):
        self._exec(
            "INSERT INTO user_skills (user_id, skill, level, updated_at)"
            " VALUES (%s, %s, %s, %s)"
            " ON CONFLICT (user_id, skill) DO UPDATE SET level=excluded.level,"
            " updated_at=excluded.updated_at",
            (user_id, skill, float(level), _now()),
        )
        return {"skill": skill, "level": float(level)}

    def list_skills(self, user_id):
        return self._all(
            "SELECT skill, level, updated_at FROM user_skills WHERE user_id = %s"
            " ORDER BY skill",
            (user_id,),
        )

    # ---- 健康 / 統計 ----
    def stats(self):
        def _count(table):
            return self._one(f"SELECT COUNT(*) AS n FROM {table}")["n"]
        return {
            "backend": "postgres_pgvector",
            "papers": _count("papers"),
            "users": _count("users"),
            "conversations": _count("conversations"),
            "interactions": _count("interactions"),
            "feeds": _count("feeds"),
            "vectors": _count("paper_embeddings"),
        }

    def close(self):
        self._conn.close()
